name: CI Pipeline

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: run bash command
        run: |
          if ! bash -n status-check.sh; then
            echo "::error::Este é um erro de sintaxe no arquivo status-check.sh!"
            exit 1
          else
            echo "::warning::Tem um aviso de sintaxe no arquivo status-check.sh!"
          fi
        shell: bash
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: test execution
        run: echo "Running tests" && exit 0
  package:
    needs: [validate, test]
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: create zip file
        run: |
          mkdir -p reports
          echo "Report" > reports/report.txt
          zip -r report.zip reports/

      - name: upload zip file
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip

      - name: Job Summary
        run: |
          echo "=== Sumary ===" >> $GITHUB_STEP_SUMMARY
          echo "OS - $RUNNER_OS" >> $GITHUB_STEP_SUMMARY
          echo "BRANCH - $GITHUB_BRANCH" >> $GITHUB_STEP_SUMMARY
        env:
          RUNNER_OS: ${{ runner.os }}
          GITHUB_BRANCH: ${{ github.ref_name }}
